### ISSUE TITLE
App stopped updating

### ISSUE THREAD

**Issue by sturgman** [rl-king/elm-hnpwa#5]
I don't know if you meant for people to actually use your app or only as an example,  but the live demo has stopped updating. Great job by the way!

**Comment by rl-king** [comment]
Ah thanks noticing! Would be nice if it's actually usable 🙂

Apparently the official hnpwa endpoint stopped fetching new data so once that's fixed this will be too
https://github.com/tastejs/hacker-news-pwas/issues/165

**Comment by rl-king** [comment]
Seems to be fixed

**Comment by sturgman** [comment]
Working here! Thanks.
