### ISSUE TITLE
network error

### ISSUE THREAD

**Issue by neocris** [rl-king/elm-hnpwa#7]
there seems to be an issue with the api endpoint and all the feeds return `NetworkError | You seem to be offline` message. it seems the issue is caused by a redirect at the server (http 301 return status) not properly accounted for. i changed the call on `toFeedData` function (line 167 on Route.elm source) from `Builder.absolute` to `Builder.relative` and it seems to work now. thanks

**Comment by rl-king** [comment]
Thanks, fixed it!
